spring:
  application:
    name: Raktbhet
  profiles:
    active: mysql

---
# MySQL profile – use this when you have MySQL running locally or remotely
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/RAKTBHET
    username: tushar2
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO
    com.sparkCoder.raktbhet.securityconfig: DEBUG
    com.sparkCoder.raktbhet.controller: DEBUG
    com.sparkCoder.raktbhet.service: DEBUG
    com.sparkCoder.raktbhet.tokenutility: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8081